import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DB_HOST: z.string().min(1),
    DB_USERNAME: z.string().min(1),
    DB_PASSWORD: z.string().min(1),
    DB_URL: z.string().url().min(1),
    NEXTAUTH_URL: z.string().min(1),
    AUTH_SECRET: z.string().min(1),
    GITHUB_ID: z.string().min(1),
    GITHUB_SECRET: z.string().min(1),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    OUR_AWS_REGION: z.string().min(1),
    OUR_AWS_ACCESS_KEY_ID: z.string().min(1),
    OUR_AWS_SECRET_ACCESS_KEY: z.string().min(1),
    RESEND_API_KEY: z.string().min(1),
    AUTH_TRUST_HOST: z.string().optional(),
    VERCEL: z.string().optional(),
    NODE_ENV: z.string(),
    VERCEL_URL: z.string().optional(),
    RENDER_INTERNAL_HOSTNAME: z.string().optional(),
    PORT: z.string().optional(),
    CI: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_MAX_FILE_SIZE_BYTES: z.string().min(1),
  },
  runtimeEnv: {
    DB_HOST: process.env.DB_HOST,
    DB_USERNAME: process.env.DB_USERNAME,
    DB_PASSWORD: process.env.DB_PASSWORD,
    DB_URL: process.env.DB_URL,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    GITHUB_ID: process.env.GITHUB_ID,
    GITHUB_SECRET: process.env.GITHUB_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    OUR_AWS_REGION: process.env.OUR_AWS_REGION,
    OUR_AWS_ACCESS_KEY_ID: process.env.OUR_AWS_ACCESS_KEY_ID,
    OUR_AWS_SECRET_ACCESS_KEY: process.env.OUR_AWS_SECRET_ACCESS_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    AUTH_TRUST_HOST: process.env.AUTH_TRUST_HOST,
    VERCEL: process.env.VERCEL,
    NODE_ENV: process.env.NODE_ENV,
    VERCEL_URL: process.env.VERCEL_URL,
    RENDER_INTERNAL_HOSTNAME: process.env.RENDER_INTERNAL_HOSTNAME,
    PORT: process.env.PORT,
    CI: process.env.CI,
    NEXT_PUBLIC_MAX_FILE_SIZE_BYTES: process.env.NEXT_PUBLIC_MAX_FILE_SIZE_BYTES,
  },
});
